### ISSUE TITLE
.no url

### ISSUE THREAD

**Issue by jkiddo** [HL7Norway/Nordics-on-FHIR#1]
https://github.com/HL7Norway/Nordics-on-FHIR/blob/6bf41dfabc7dda12a9a06efa0d3cea2001f91b05/StructureDefinition/nordic-middlename.structuredefinition-extension.xml#L459

Just to be sure - until something else is established, the URL's are going to be fixed to hl7.no org?

**Comment by rockphotog** [comment]
@thomiz proposal is now http://hl7.nordic/fhir/StructureDefinition/nordic-middlename . 

As an URI, it does not need to be resolvable (but should be in the future).

**Comment by jkiddo** [comment]
See #2

**Comment by rockphotog** [comment]
Aha! :-)

**Comment by thomiz** [comment]
I don't know how that happened, I guess I can blame Forge. Thanks for the patch @jkiddo
